# Generated by Django 5.1.3 on 2024-11-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraftBukkit',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('FabricVersion', models.CharField(max_length=20)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Forge',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('ForgeVersion', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=15)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mohist',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('ForgeVersion', models.CharField(max_length=20)),
                ('BuildNumber', models.IntegerField()),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NeoForge',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('NeoForgeVersion', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=15)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('BuildNumber', models.IntegerField()),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Spigot',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpongeForge',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('ForgeVersion', models.CharField(max_length=20)),
                ('SpongeVersion', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=15)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpongeNeo',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('NeoForgeVersion', models.CharField(max_length=20)),
                ('SpongeVersion', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=15)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpongeVanilla',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('SpongeVersion', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=15)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vanilla',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=15)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
    ]
