# Generated by Django 5.1.3 on 2024-11-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrock',
            fields=[
                ('MCVersion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=15)),
                ('URL', models.URLField(max_length=150)),
                ('ThirdPartySourceURL', models.URLField(max_length=150)),
            ],
        ),
    ]
